### ISSUE TITLE
Symlink ewwwio_is_file problem

### ISSUE THREAD

**Issue by EdwardBock** [nosilver4u/ewww-image-optimizer#224] opened 2021-04-30 11:39 UTC
**Describe the bug**

WordPress.org Support Ticket: https://wordpress.org/support/topic/symlink-ewwwio_is_file-problem/#post-14383943

We want to use your plugin and had some troubles in combination with our hoster freistilbox.com . For security reasons all code is readonly and can only be deployed via git. Every apache writable folder is symlinked into the system. So the ewww folder in wp-content is a symlink to a folder on our storage server.

The function ewwwio_is_file in common.php tries to check folder paths by resolving the realpath. That does not work with symlinks. That’s why we got the error that webp is missing even though it was not. We commented out the lines 3560-3567 (stable tag 6.1.2) and now it works fine.

**To Reproduce**
1. Symlink /wp-content/ewww to a folder that is outside the docroot
2. Try to install and use the plugin
3.  It won't work because it cannot find scrits in ewww

**Expected behavior**
It should work even if ewww is a symlink.

**Comment by nosilver4u** [comment] 2021-04-30 13:54
Are all the writable folders linked to (sub-folders of) a common folder on the storage server?

**Comment by EdwardBock** [comment] 2021-05-03 06:03
Yes. It looks something like this.

**storage mount:** `~/current/public/`
**docroot:** `~/current/docroot/`

The storage mount contains all writable stuff like `~/current/public/wp-content/uploads/` which is symliked to `~/current/docroot/wp-content/uploads/`

There can be some other symlinks too like `~/current/public/wp-content/ewww/` which is symlinked to `~/current/docroot/wp-content/ewww`.

Those folders are gitignored and configured in a Boxfile. The deployment will then make all code and files readonly in the deployment task except for those symlinked writable folders.

**Comment by nosilver4u** [comment] 2021-05-06 17:38
Alright, so from what I've gathered here, the problem is that all these exist in the docroot:
wp-content/
/ (WP's ABSPATH)
Thus wp-content/ewww/, which is located in the storage mount and symlinked into the docroot, doesn't match any of these.
I was originally thinking to add a user-configurable match into the list, but then I had another thought, which would be to run realpath on EWWW_IMAGE_OPTIMIZER_TOOL_PATH, and back it out one level, which would allow us to validate any file in ~/current/public/wp-content/

To that end, I've just committed a potential fix to GitHub. Please let me know if it works well for you: https://docs.ewww.io/article/73-update-from-github

**Comment by EdwardBock** [comment] 2021-05-07 06:02
If you could just bugfix the defined check than this is working for our setup, yes 👍

https://github.com/nosilver4u/ewww-image-optimizer/blob/master/common.php#L3561

```php
if ( defined( 'EWWW_IMAGE_OPTIMIZER_TOOL_PATH' ) ) {
...
}
```

**Comment by nosilver4u** [comment] 2021-05-07 14:16
What do you mean by "bugfix the defined check"? Are you encountering some other error with the updated code?

**Comment by nosilver4u** [comment] 2021-05-07 14:45
Oh good grief! And of course it doesn't throw an error, because EWWW_IMAGE_OPTIMIZER_TOOL_PATH is normally defined, and so it interprets the actual tool path as the constant name...
Thanks for catching that, I've just committed the fix :+1:

**Comment by EdwardBock** [comment] 2021-05-08 11:25
Yes sorry, no error, but it did not work as expected 😁

Thanks for you quick help with this!

**Closed** 2021-05-08 11:26 UTC
Labels: bug
