### ISSUE TITLE
PHP8+ Undefined property

### ISSUE THREAD

**Issue by TokyoJump** [nosilver4u/ewww-image-optimizer#288] opened 2022-09-16 08:53 UTC
**Describe the bug**
Contains the warning "undefined property" in PHP8 and later.

**To Reproduce**
A warning occurs mainly when updating some plugins in the PHP8 or later environment

**How to fix**

This is the debug information

Warning: Undefined property: EIO_Backup::$backup_uploads_dir in /site/wp-content/plugins/ewww-image-optimizer/classes/class-eio-backup.php on line 120
Warning: Undefined property: EIO_Backup::$backup_uploads_dir in /site/wp-content/plugins/ewww-image-optimizer/classes/class-eio-backup.php on line 121

$this->backup_uploads_dir have no property.

It's not a problem before PHP8, but it's a problem after PHP8.

just define isset

**Comment by nosilver4u** [comment] 2022-09-16 14:56
duplicate of #286

**Closed by nosilver4u** 2022-09-16 14:56 UTC
