### ISSUE TITLE
PHP Warning: Incorrect APP1 Exif Identifier Code

### ISSUE THREAD

**Issue by dreamon11** [nosilver4u/ewww-image-optimizer#187] opened 2020-06-29 12:57 UTC
Hello,

I have frequently this PHP Warning:
```
exif_read_data(photo-5ef93dfac767c.jpg): Incorrect APP1 Exif Identifier Code in /plugins/ewww-image-optimizer/common.php on line 6344
```

Request:
```
POST /wp/wp-admin/admin-ajax.php?action=wp_ewwwio_media_optimize&nonce=750d4f4d32
```

Backtrace:
```
#0 (): App\{closure}(2, 'exif_read_data(photo-5ef93dfac767c.jpg): Incorrect APP1 Exif Identifier Code', '/plugins/ewww-image-optimizer/common.php', '6344', Array)
#1 /plugins/ewww-image-optimizer/common.php(6344): exif_read_data('/uploads/2020/06/photo-5ef93dfac767c.jpg')
#2 /plugins/ewww-image-optimizer/common.php(5940): ewww_image_optimizer_get_orientation('/uploads/2020/06/photo-5ef93dfac767c.jpg', 'image/jpeg')
#3 /plugins/ewww-image-optimizer/unique.php(1914): ewww_image_optimizer_autorotate('/uploads/2020/06/photo-5ef93dfac767c.jpg')
#4 /plugins/ewww-image-optimizer/common.php(6838): ewww_image_optimizer('/uploads/2020/06/photo-5ef93dfac767c.jpg', 1, false, true, true)
#5 /plugins/ewww-image-optimizer/classes/class-ewwwio-media-background-process.php(99): ewww_image_optimizer_resize_from_meta_data(Array, '171688', true, '1')
#6 /plugins/ewww-image-optimizer/classes/class-ewwwio-background-process.php(306): task(Array)
#7 /plugins/ewww-image-optimizer/classes/class-ewwwio-background-process.php(186): handle()
#8 /wp/wp-includes/class-wp-hook.php(287): maybe_handle('')
#9 /wp/wp-includes/class-wp-hook.php(311): apply_filters('', Array)
#10 /wp/wp-includes/plugin.php(478): do_action(Array)
#11 /wp/wp-admin/admin-ajax.php(190): do_action('wp_ajax_nopriv_wp_ewwwio_media_optimize')
```

Is there a way to fix this?

Thanks!

**Comment by nosilver4u** [comment] 2020-06-29 14:12
I'm not sure if there is, since we have error suppression enabled for that function call, so it shouldn't even throw any warnings.
Can you please provide your WP version, PHP version, and sample images for reproducing the error?

**Comment by dreamon11** [comment] 2020-07-01 13:47
This warning shows only in PHP error log, not in front end.

I don't know which images cause this warning, I will try to print the source if it occurs next time.

WordPress 5.4.2
PHP 7.3.17

**Comment by nosilver4u** [comment] 2020-07-01 13:57
No problem, just let me know when you find an image to reproduce the warning. I have tons of test images, but none that trigger that particular message!

**Comment by dreamon11** [comment] 2020-07-02 08:30
I have an image which producing the PHP warning.

How can I send you it? (it's a private image)

**Comment by nosilver4u** [comment] 2020-07-02 14:24
send it via https://ewww.io/contact-us/ and reference this issue

**Comment by nosilver4u** [comment] 2020-07-11 22:43
Somehow I seem to have lost track of this. I thought I saw you sent an image, but I can't find it now, could you send it once more please?

**Comment by nosilver4u** [comment] 2020-08-11 13:17
closing this until I can get my hands on an image that produces the warnings

**Closed by nosilver4u** 2020-08-11 13:17 UTC
Labels: more info
