### ISSUE TITLE
Warning on array value due to improper condition order

### ISSUE THREAD

**Issue by jameshgordy** [nosilver4u/ewww-image-optimizer#340] opened 2024-10-30 09:51 UTC
https://github.com/nosilver4u/ewww-image-optimizer/blob/7f4173204f477dc4976ff3b6033ec8b27145d764/common.php#L8216

My project was receiving extensive warnings like this:

`Undefined array key 0 in /projects/xyz/public_html/wp-content/plugins/ewww-image-optimizer/common.php on line 8174`

This is due to validating an array value that is being request potentially after an existence check - as per [PHP Operator Precedence](https://www.php.net/manual/en/language.operators.precedence.php) which indicates the logic is left to right due to the || operator.

A preferred option would be adding a falsifiable alternative perhaps? 

`	if ( ! is_array( $duplicates ) || ! is_array( $duplicates[0] ?? false ) ) {
		return false;
	}`

**Comment by nosilver4u** [comment] 2024-10-30 16:16
Thanks for reporting that, we'll get it fixed soon! I reworked that function a while back, so I suspect this bug slipped in then.

**Comment by nosilver4u** [comment] 2024-11-13 20:09
Fixed in #344.
We also found what I believe was the root cause, so two fixes in one!

**Closed by nosilver4u** 2024-11-13 20:09 UTC
