### ISSUE TITLE
Lazt load: Threshold

### ISSUE THREAD

**Issue by yoyurec** [nosilver4u/ewww-image-optimizer#296] opened 2023-04-01 23:47 UTC
Threshold is really useful parameter, but currently it should be configured via PHP `EIO_LL_THRESHOLD` ((
Suggest to add it as input option in plugin Lazt load section. Tnx

**Comment by nosilver4u** [comment] 2023-04-03 15:45
duplicate of feature request: https://feedback.ewww.io/b/features/p/lazt-load-threshold

**Closed by nosilver4u** 2023-04-03 15:45 UTC
