### ISSUE TITLE
WebP generation ignores tinypng optimized images.

### ISSUE THREAD

**Issue by pratham2003** [nosilver4u/ewww-image-optimizer#171] opened 2020-04-09 07:13 UTC
**Describe the bug**
Webp Only bulk conversion ignores images optimized by tinypng (other plugins?) even if a webp file is not present. The only way around this is force updating all existing images.

My scenario.
I have 500 images in /abc/wp-content/uploads which are already force optimized by ewwio.
I then added /abc/wp-content/themes/xyc/images/ folder to be optimized but these images were already optimized by another tinypng plugin I think. The plugin skips generating webp for the images in themes folder.

**Sample Images**
ewwwio's webp generation ignores tinypng compression information.

**Comment by nosilver4u** [comment] 2020-04-15 18:20
After looking through the code, I realized that was really "by design", but it isn't very intuitive. So the next release will bypass the TinyPNG check when in WebP Only mode (will be included in the next git commit if you want the code earlier).

**Closed by nosilver4u** 2020-04-15 18:20 UTC
