### ISSUE TITLE
Gif upload doesn't work on AWS S3 with WP Offload Media 

### ISSUE THREAD

**Issue by smazelerat-insita** [nosilver4u/ewww-image-optimizer#306] opened 2024-01-17 11:16 UTC
**Describe the bug**
When i upload a GIF media into WP library, the media isn't upload to AWS S3

**To Reproduce**
1. Go to 'Media Library'
2. Click on 'Add New Media File'
3. Upload a Gif file
4. See error, media hasn't thumbnail and doesn't load on preview.

**Expected behavior**
Gif media upload to S3 like other media (work's with jpg and png)

**Screenshots**
![SceenShot_2024-01-17 113515](https://github.com/nosilver4u/ewww-image-optimizer/assets/16941549/d093fa8c-34fa-4976-8ddd-a4f54e101b1f)

**Debugging Information (please enable the debugging information from the plugin settings, redact as necessary):**
```
EWWW\Base::__construct()
plugin (resource) content_url: https://preprod.flunch.fr/wp-content/ewww/
plugin (resource) content_dir: /srv/www/preprod.flunch.fr/current/wp-content/ewww/
home url: https://preprod.flunch.fr/
relative home url: //preprod.flunch.fr/
home domain: preprod.flunch.fr
EWWW\Plugin::instance()
EWWW\Backup::__construct()
EWWW\Local::__construct()
EWWW\Local::exec_check()
exec appears to be disabled
EWWW\Local::disable_tools()
EWWW\Local::skip_tools()
EWWW\Plugin::cloud_init()
ewww_image_optimizer_load_plugin_compat()
checking active plugins
ewww_image_optimizer_init()
EWWW\Tracking::schedule_send()
ewww_image_optimizer_upgrade()
saving network settings
network-wide settings, no override
ewww_image_optimizer_jpg_background()
ewww_image_optimizer_jpg_quality()
ewww_image_optimizer_webp_quality()
ewww_image_optimizer_avif_quality()
ewww_image_optimizer_aux_paths_sanitize()
EWWW\Base::exclude_paths_sanitize()
EWWW\Base::exclude_paths_sanitize()
EWWW\Base::exclude_paths_sanitize()
EWWW\Base::exclude_paths_sanitize()
EWWW\Plugin::register_settings()
EWWW\Plugin::cloud_init()
EWWW\Plugin::exec_init()
ewww_image_optimizer_cron_setup()
un-scheduling ewww_image_optimizer_auto
EWWW\Plugin::tool_init()
EWWW\Local::install_tools()
Checking/Installing tools in /srv/www/preprod.flunch.fr/current/wp-content/ewww/
EWWW\Local::skip_tools()
wp-content/ewww permissions: 0775
EWWW\Local::install_paths()
CPU architecture: x86_64
generated paths:
/srv/www/preprod.flunch.fr/current/wp-content/plugins/ewww-image-optimizer/binaries/jpegtran-linux
/srv/www/preprod.flunch.fr/current/wp-content/plugins/ewww-image-optimizer/binaries/optipng-linux
/srv/www/preprod.flunch.fr/current/wp-content/plugins/ewww-image-optimizer/binaries/gifsicle-linux
/srv/www/preprod.flunch.fr/current/wp-content/plugins/ewww-image-optimizer/binaries/pngquant-linux
/srv/www/preprod.flunch.fr/current/wp-content/plugins/ewww-image-optimizer/binaries/cwebp-linux
/srv/www/preprod.flunch.fr/current/wp-content/ewww/jpegtran
/srv/www/preprod.flunch.fr/current/wp-content/ewww/optipng
/srv/www/preprod.flunch.fr/current/wp-content/ewww/gifsicle
/srv/www/preprod.flunch.fr/current/wp-content/ewww/pngquant
/srv/www/preprod.flunch.fr/current/wp-content/ewww/cwebp
Linux/UNIX style OS, checking permissions
ewww_image_optimizer_load_editor()
loading image editors: EWWWIO_Imagick_Editor
EWWWIO_GD_Editor
WP_Image_Editor_Imagick
WP_Image_Editor_GD
ewww_image_optimizer_bulk_script()
ewww_image_optimizer_tool_script()
ewww_image_optimizer_webp_script()
ewww_image_optimizer_settings_script()
EWWW\Base::content_url()
wp-content/uploads/
site/upload url: https://preprod.flunch.fr
site/upload domain: preprod.flunch.fr
upload_url: https://preprod.flunch.fr/wp-content/uploads/
ewww_image_optimizer_easy_site_registered()
EWWW\Plugin::notice_utils()
EWWW\Local::exec_check()
ewww_image_optimizer_network_options()
ewww_image_optimizer_options()
ewww_image_optimizer_savings()
savings query avoided via (multi-site) cache
deployer
EWWW IO version: 723
WP version: 6.4.1
PHP version: 70433
libxml version: 20910
core plugin
ABSPATH: /srv/www/preprod.flunch.fr/current/
WP_CONTENT_DIR: /srv/www/preprod.flunch.fr/current/wp-content
EWWWIO_CONTENT_DIR: /srv/www/preprod.flunch.fr/current/wp-content/ewww/
home url (Site URL): https://preprod.flunch.fr
site url (WordPress URL): https://preprod.flunch.fr
wp_upload_dir (baseurl): https://preprod.flunch.fr/wp-content/uploads
wp_upload_dir (basedir): /srv/www/preprod.flunch.fr/current/wp-content/uploads
content_width:
registered stream wrappers: https,ftps,compress.zlib,php,file,glob,data,http,ftp,zip,phar
allowing multisite override: no
not external cache
EWWW\Base::gd_support()
GD found, supports:
GD Version: 2.3.0
FreeType Support: 1
FreeType Linkage: with freetype
GIF Read Support: 1
GIF Create Support: 1
JPEG Support: 1
PNG Support: 1
WBMP Support: 1
XPM Support: 1
XBM Support: 1
WebP Support: 1
BMP Support: 1
TGA Read Support: 1
JIS-mapped Japanese Font Support:
EWWW\Base::gmagick_support()
EWWW\Base::imagick_support()
3FR,3G2,3GP,AAI,AI,APNG,ART,ARW,AVI,AVIF,AVS,BGR,BGRA,BGRO,BIE,BMP,BMP2,BMP3,BRF,CAL,CALS,CANVAS,CAPTION,CIN,CIP,CLIP,CMYK,CMYKA,CR2,CR3,CRW,CUR,CUT,DATA,DCM,DCR,DCX,DDS,DFONT,DNG,DPX,DXT1,DXT5,EPDF,EPI,EPS,EPS2,EPS3,EPSF,EPSI,EPT,EPT2,EPT3,ERF,FAX,FILE,FITS,FRACTAL,FTP,FTS,G3,G4,GIF,GIF87,GRADIENT,GRAY,GRAYA,GROUP4,H,HALD,HDR,HEIC,HISTOGRAM,HRZ,HTM,HTML,HTTP,HTTPS,ICB,ICO,ICON,IIQ,INFO,INLINE,IPL,ISOBRL,ISOBRL6,J2C,J2K,JBG,JBIG,JNG,JNX,JP2,JPC,JPE,JPEG,JPG,JPM,JPS,JPT,JSON,K25,KDC,LABEL,M2V,M4V,MAC,MAGICK,MAP,MASK,MAT,MATTE,MEF,MIFF,MKV,MNG,MONO,MOV,MP4,MPC,MPG,MRW,MSL,MTV,MVG,NEF,NRW,NULL,ORF,OTB,OTF,PAL,PALM,PAM,PATTERN,PBM,PCD,PCDS,PCL,PCT,PCX,PDB,PDF,PDFA,PEF,PES,PFA,PFB,PFM,PGM,PGX,PICON,PICT,PIX,PJPEG,PLASMA,PNG,PNG00,PNG24,PNG32,PNG48,PNG64,PNG8,PNM,POCKETMOD,PPM,PREVIEW,PS,PS2,PS3,PSB,PSD,PTIF,PWP,RADIAL-GRADIENT,RAF,RAS,RAW,RGB,RGBA,RGBO,RGF,RLA,RLE,RMF,RW2,SCR,SCT,SFW,SGI,SHTML,SIX,SIXEL,SPARSE-COLOR,SR2,SRF,STEGANO,SUN,TEXT,TGA,THUMBNAIL,TIFF,TIFF64,TILE,TIM,TTC,TTF,TXT,UBRL,UBRL6,UIL,UYVY,VDA,VICAR,VID,VIDEO,VIFF,VIPS,VST,WBMP,WEBM,WEBP,WMV,WPG,X,X3F,XBM,XC,XCF,XPM,XPS,XV,XWD,YCbCr,YCbCrA,YUV
EWWW\Base::gd_supports_webp()
EWWW\Base::gd_support()
yes it does
EWWW\Base::imagick_supports_webp()
EWWW\Base::imagick_support()
yes it does
EWWW\Local::exec_check()
480 images have been optimized
automatic compression enabled
remove metadata: on
jpg level:
png level:
gif level:
pdf level:
svg level:
bulk delay:
backup mode:
cloudinary upload: off
ExactDN enabled: off
ExactDN all the things: on
ExactDN lossy: 1
ExactDN resize existing: off
ExactDN attachment queries: on
Easy IO exclusions:

add missing dimensions: off
lazy load: off
ewwwio_other_lazy_detected()
LL autoscale: on
LQIP: off
S(VG)IIP: off
external CSS background (all things):
LL exclusions:

optipng level: 2
pngout disabled: yes
pngout level: 2
svgcleaner disabled: yes
ewww_image_optimizer_jpg_quality()
configured quality: 82
ewww_image_optimizer_jpg_quality()
effective quality: 82
ewww_image_optimizer_webp_quality()
effective WebP quality: 75
sharpen: no
background optimization: on
scheduled optimization: off
include media library: on
include originals: off
folders to optimize:

folders to ignore:

skip images smaller than: bytes
skip PNG images larger than: bytes
exclude originals from lossy: off
exclude originals from metadata removal: off
use system binaries: no
resize detection: off
max media dimensions: 0 x 0
max other dimensions: x
resize existing images: off
resize existing (non-media) images: off
ewww_image_optimizer_get_image_sizes()
sizes: thumbnail
medium
medium_large
large
1536x1536
2048x2048
Array
(
[thumbnail] => Array
(
[width] => 150
[height] => 150
[crop] => 1
)
[medium] => Array
(
[width] => 300
[height] => 300
[crop] =>
)
[medium_large] => Array
(
[width] => 768
[height] => 9999
[crop] =>
)
[large] => Array
(
[width] => 1024
[height] => 1024
[crop] =>
)
[1536x1536] => Array
(
[width] => 1536
[height] => 1536
[crop] =>
)
[2048x2048] => Array
(
[width] => 2048
[height] => 2048
[crop] =>
)
[pdf-full] => Array
(
[width] => 99999
[height] => 99999
[crop] =>
)
)

disabled sizes:
thumbnail: optimization=+ creation=+
medium: optimization=+ creation=+
medium_large: optimization=+ creation=+
large: optimization=+ creation=+
1536x1536: optimization=+ creation=+
2048x2048: optimization=+ creation=+
pdf-full: optimization=+ creation=+
delete originals: off
jpg2png: off
png2jpg: off
gif2png: off
png2jpg fill:
ewww_image_optimizer_jpg_background()
webp conversion: on
js webp rewriting: off
picture webp rewriting: off
WebP Rewrite exclusions:

webp paths:

forced webp: off
forced gif2webp: on
enable help beacon: no
origin (SERVER_ADDR): 10.50.1.5
checking 13.224.81.112 from gethostbyname
not a Cloudflare host: 13.224.81.112
PHP module: fpm-fcgi
possibly missing mod_rewrite
possibly missing mod_headers
ewww_image_optimizer_test_webp_mime_error()
webp mime check failed: 89504e
ewww_image_optimizer_webp_rewrite_verify()
checking 13.224.81.14 from gethostbyname
not a Cloudflare host: 13.224.81.14
ewww_image_optimizer_htaccess_path()
using /srv/www/preprod.flunch.fr/current/.htaccess
current rules:
missing or invalid rules
webp .htaccess rules not detected
max_execution_time: 30
ewww_image_optimizer_stl_check()
set_time_limit allowed
disable_functions: apache_child_terminate,apache_getenv,apache_get_modules,apache_get_version,apache_note,apache_setenv,exec,passthru,pcntl_alarm,pcntl_async_signals,pcntl_exec,pcntl_fork,pcntl_get_last_error,pcntl_getpriority,pcntl_setpriority,pcntl_signal,pcntl_signal_dispatch,pcntl_signal_get_handler,pcntl_sigprocmask,pcntl_sigtimedwait,pcntl_sigwaitinfo,pcntl_strerror,pcntl_wait,pcntl_waitpid,pcntl_wexitstatus,pcntl_wifexited,pcntl_wifsignaled,pcntl_wifstopped,pcntl_wstopsig,pcntl_wtermsig,popen,proc_open,shell_exec,system,virtual
sleep allowed
detected memory limit is: 536870912
```
**Sample Images**
![Test-GIF_3Menus](https://github.com/nosilver4u/ewww-image-optimizer/assets/16941549/97fc350f-a4f5-4a8f-a4fb-ae49802ed761)

**Additional context**
- Wordpress multisite
- Multi-server
- EWWW Image Optimizer 7.2.3 (network activated)
- WP Offload Media 3.2.6 (network activated)

_When disabling EWWW Image Optimizer plugin, Gif offload on S3 works_

**Comment by nosilver4u** [comment] 2024-01-17 15:48
Please check your server error logs, I cannot reproduce the issue with the image you provided. It uploads nearly instantly on my test site with no issues at all.

**Comment by nosilver4u** [comment] 2024-01-17 15:49
Hold that thought, forgot to test it on my WPOM site!

**Comment by nosilver4u** [comment] 2024-01-17 16:48
So, it turns out we had an issue that only triggers on servers with exec() disabled (and no API key). This causes no thumbnails to be generated, and WP Offload Media won't offload an image until the thumbs have been generated.

The issue is fixed now, so you can grab the latest code on Github, or use our link at https://docs.ewww.io/article/73-update-from-github
*The latter repacks the Github zip file without the annoying '-master' suffix on the plugin folder.

**Closed by nosilver4u** 2024-01-17 16:48 UTC
Labels: bug

**Comment by smazelerat-insita** [comment] 2024-01-17 16:50
> Huh, that's interesting, I'll have to dig into it more. Can you also post your WPOM diagnostic info, to make sure we can match your config there (as much as is possible)?

```
site_url(): https://preprod.flunch.fr
home_url(): https://preprod.flunch.fr
Database Name: xxx
Table Prefix: mag_13_
WordPress: 6.4.1 Multisite (subdirectory)
Multisite Site Count: 2
Domain Mapping: Disabled
Web Server: Apache
PHP: 7.4.33
MySQL: 5.5.5
ext/mysqli: yes
PHP Memory Limit: 512M
WP Memory Limit: 64M
Memory Usage: 2 Mo
Blocked External HTTP Requests: None
WP Locale: fr_FR
Organize offloads by month/year: Enabled
WP_DEBUG: No
WP_DEBUG_LOG: No
WP_DEBUG_DISPLAY: Yes
SCRIPT_DEBUG: No
WP Max Upload Size: 10 Mo
PHP Time Limit: 30
PHP Error Log: /var/log/php/php7.4-fpm-preprod.flunch.fr.error.log
WP Cron: Disabled
fsockopen: Enabled
allow_url_fopen: Disabled
OpenSSL: OpenSSL 1.1.1n  15 Mar 2022
cURL: 7.74.0
Zlib Compression: Enabled
PHP GD: 2.3.0
Imagick: Enabled
Basic Auth: Disabled
Proxy: Disabled

Total Media Items: 518
Total Offloaded Media Items: 448
Total Not Offloaded Media Items: 70

Media Library Items: 518
Offloaded Media Library Items: 448
Not Offloaded Media Library Items: 70

Number of Image Sizes: 6

Names and Dimensions of Image Sizes: 
thumbnail (150x150)
medium (300x300)
large (1024x1024)
1536x1536 (1536x1536)
2048x2048 (2048x2048)

WP_CONTENT_DIR: /srv/www/preprod.flunch.fr/current/wp-content
WP_CONTENT_URL: https://preprod.flunch.fr/wp-content
UPLOADS: Not defined
WP_PLUGIN_DIR: /srv/www/preprod.flunch.fr/current/wp-content/plugins
WP_PLUGIN_URL: https://preprod.flunch.fr/wp-content/plugins

AS3CF_PROVIDER: Not defined
AS3CF_BUCKET: Not defined
AS3CF_REGION: Not defined
AS3CF_SETTINGS: Defined
AS3CF_SETTINGS Keys: provider, use-server-roles

OME Metadata Version: 12

Custom tables:
mag_13_as3cf_items: Ok

Storage Provider: Amazon S3
Use Server Roles: On
Key File Path: N/A
Access Keys Set: No
Access Key ID Define: Not defined
Secret Access Key Define: Not defined

Bucket: xxx
Region: eu-west-1
Block All Public Access: Disabled
Object Ownership Enforced: No

Offload Media: On
Remove Local Media: Off
Enable Add Prefix to Bucket Path: On
Custom Prefix for Bucket Path: wp-content/uploads/
Add Year & Month to Bucket Path: On
Add Object Version to Bucket Path: Off

Delivery Provider: Amazon CloudFront
Deliver Offloaded Media: Off
Use Custom Domain Name (CNAME): Off
Custom Domain (CNAME): preprod.flunch.fr
Serve Private Media: Off
Public Key ID Set: No
Private Key File Path: (none)
Private Bucket Path: (none)

Force HTTPS: Off

Posts Count: 5 932

Pro Upgrade: 
License Status: Valid
License Constant: Off

Background Jobs: 

Assets Pull:
Rewrite URLs: Off
Domain: preprod.flunch.fr
Force HTTPS: Off
Domain Check: <code>preprod.flunch.fr</code> must not be the same as the site domain. Use a subdomain instead.

AS3CF_ASSETS_PULL_SETTINGS: Not defined

Active Theme Name: flunch-www
Active Theme Version: 
Active Theme Folder: www-flunch

Active Plugins:
Advanced Custom Fields (v6.2.1) by WP Engine
Dicoresto (v0.2) by Insitaction
EWWW Image Optimizer (v7.2.3) by Exactement WWW
Elementor (v3.18.2) by Elementor.com
Elementor Addon for WP Offload Media compatibility (v1.0.0) by Altavia Insitaction
Elementor Pro (v3.17.1) by Elementor.com
Forecast (v0.1) by Insitaction
Import Produits (v0.1) by Insitaction
Insitaction Axeptio (v1.0) by Nhust Insitaction
JSON REST API (v1.1.1) by Ryan McCue
Post Types Order (v2.1) by Nsp Code
SSL Insecure Content Fixer (v2.7.2) by WebAware
WP Crontrol (v1.15.3) by John Blackbourn &amp; contributeurs
WP Offload Media (v3.2.6) by Delicious Brains
WP Rocket (v3.15.4) by WP Media
WPS Hide Login (v1.9.9) by WPServeur, NicolasKulka, wpformation
Yoast SEO (v21.5) by L’équipe Yoast

Must-use Plugins:
Elementor Safe Mode (v1.0.0) by Elementor.com


Drop-ins:
advanced-cache.php - advanced-cache.php
```

**Comment by smazelerat-insita** [comment] 2024-01-17 16:53
> So, it turns out we had an issue that only triggers on servers with exec() disabled (and no API key). This causes no thumbnails to be generated, and WP Offload Media won't offload an image until the thumbs have been generated.
> 
> The issue is fixed now, so you can grab the latest code on Github, or use our link at https://docs.ewww.io/article/73-update-from-github *The latter repacks the Github zip file without the annoying '-master' suffix on the plugin folder.

wow, so quickly!

Thank you very much, I will try this

**Comment by smazelerat-insita** [comment] 2024-01-18 08:43
I confirm that this resolves the problem, thank you again for your reactivity 😄
